.TH ABBTR 1 "August 2024" "Version 1.0.4" "abbtr"
.SH NAME
abbtr \- Abbreviator for long commands in Linux terminal
.SH SYNOPSIS
.B abbtr
[\fIoptions\fP] [\fIusage\fP] ...
.SH DESCRIPTION
.B abbtr
comes as an alternative to the default "alias" command. It's a simple program designed to abbreviate long prompts in the GNU/Linux terminal. You can easily set rules, delete them, list them, and update them with a clear set of parameters. It should be functional in any GNU/Linux distribution.
.SH OPTIONS
.TP
.B \-l
List stored rules.
.TP
.B \-n \fI<name> '<command>'\fP
Create a new rule with the specified \fIname\fP and \fIcommand\fP.
.TP
.B \-i \fI<file path>\fP
Import rules from a local file.
.TP
.B \-e
Export rules to a file.
.TP
.B \-b=\fI<variable:value>\fP
Predefine the value of a bottle.
.TP
.B \-r \fI<name>\fP
Delete an existing rule by \fIname\fP.
.TP
.B \-r a
Delete all rules.
.TP
.B \-c \fI<name> '<command'\fP>
Update the command of an existing rule specified by \fIname\fP.
.TP
.B \-ln \fI<name>\fP
Show the contents of a specific rule by \fIname\fP.
.TP
.B \-h
Show this help message.
.TP
.B \-v
Show the program version.
.SH USAGE EXAMPLES
Create a new rule:
.B abbtr \-n update 'sudo apt update -y'
.P
Then run:
.B update
.P
Syntax for feeding bottles:
.B b%('variable')%b
.SH USER FILES
.B Config file:
located at ~/.config/abbtr/abbtr.conf
.P
.B Log file:
located at ~/.local/share/abbtr/abbtr.log
.P
.B rule scripts:
located at ~/.local/bin
.P
.SH BUGS
.B abbtr
does not have any locking mechanisms yet.
.P
If you discover any other bugs in \fBabbtr\fP, please contact the author.
.SH SEE ALSO
.B abbtr-info(1),
.B abbtr User Manual
(/usr/share/doc/abbtr/abbtr.1).
.P
Packaging tools:
.B debhelper(7),
.B dh_make(8),
.B dpkg-buildpackage(1).
.SH AUTHORS
Originally written by Manuel Guerra <ar.manuelguerra@gmail.com>.
.P
Please use the email address <ar.manuelguerra@gmail.com> for abbtr-related comments.
.SH COPYRIGHT
Copyright © 2024 Manuel Guerra
.P
License: BSD-3-Clause
.PP
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are
 met:
.PP
 .
.PP
    * Redistributions of source code must retain the above copyright
 notice, this list of conditions and the following disclaimer.
.PP
    * Redistributions in binary form must reproduce the above
 copyright notice, this list of conditions and the following disclaimer
 in the documentation and/or other materials provided with the
 distribution.
.PP
    * Neither the names of the authors nor the names of the
 contributors may be used to endorse or promote products derived from
 this software without specific prior written permission.
.PP
 .
.PP
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
